### ISSUE TITLE
Missiles not targeting

### ISSUE THREAD

**Issue by Seldon3** [DankuwOs/CustomWeaponBase#3]
With the new  v1.10.1  Missiles no longer target  air to air   or  air to ground. Any Thoughts. Thanks
Please find attached zip file. of most resent flight.
[Info.txt](https://github.com/user-attachments/files/16489108/Info.txt)
[Launcher Log.txt](https://github.com/user-attachments/files/16489109/Launcher.Log.txt)
[Log VTPatcher.txt](https://github.com/user-attachments/files/16489110/Log.VTPatcher.txt)
[Player.log](https://github.com/user-attachments/files/16489111/Player.log)

Missiles track straight to the ground.

**Comment by KaveXD** [comment]
Same issue as #2

**Comment by DankuwOs** [comment]
Fixed :~)

**Comment by Seldon3** [comment]
Thanks for your response and efforts. Works fine for me now.
